[[CSPICE]]
arch = "aarch64"
git-tree-sha1 = "be26a9451437a875a96120e0ee07ad8c5180e477"
libc = "glibc"
os = "linux"

    [[CSPICE.download]]
    sha256 = "7a8408483f644d386c2cbdf031c2df810480ab0de2f1d67c56897f4244f82c67"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.0.0+1/CSPICE.v66.0.0.aarch64-linux-gnu.tar.gz"
[[CSPICE]]
arch = "aarch64"
git-tree-sha1 = "b0269ede6ba265c04a7925b7272d67a71e7bd090"
libc = "musl"
os = "linux"

    [[CSPICE.download]]
    sha256 = "07433f58e7bca6cc81b46f1e8e243983640d0cd3d2f5a996cbd9273771b21671"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.0.0+1/CSPICE.v66.0.0.aarch64-linux-musl.tar.gz"
[[CSPICE]]
arch = "armv7l"
git-tree-sha1 = "60b945f94cdc32124fae74bdc22a096584471506"
libc = "glibc"
os = "linux"

    [[CSPICE.download]]
    sha256 = "49dc5959443dd5435f8d977211939ca63021af66fa8e2b5cbf25807e204deb3f"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.0.0+1/CSPICE.v66.0.0.armv7l-linux-gnueabihf.tar.gz"
[[CSPICE]]
arch = "armv7l"
git-tree-sha1 = "85323b0d04c30973f907ab0848cde8c9196bd64e"
libc = "musl"
os = "linux"

    [[CSPICE.download]]
    sha256 = "f36700d6e409179a95ee3de9d78f2f1e914ba5b4eca97cc795179a6697ef34f7"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.0.0+1/CSPICE.v66.0.0.armv7l-linux-musleabihf.tar.gz"
[[CSPICE]]
arch = "i686"
git-tree-sha1 = "bebc67a698a7d23d72b33e563ee299f59cb56c5e"
libc = "glibc"
os = "linux"

    [[CSPICE.download]]
    sha256 = "dfd725531eb59d1ffbedea1da1c818a23f8c833e9738d46fcee17d955a10615e"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.0.0+1/CSPICE.v66.0.0.i686-linux-gnu.tar.gz"
[[CSPICE]]
arch = "i686"
git-tree-sha1 = "74ccbc3ea693aaf6e25e91d1e6c3e5887c11d10b"
libc = "musl"
os = "linux"

    [[CSPICE.download]]
    sha256 = "3824311614dbd0433f0084c4629d47fe162e2f50e8a2994898488d264580d579"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.0.0+1/CSPICE.v66.0.0.i686-linux-musl.tar.gz"
[[CSPICE]]
arch = "i686"
git-tree-sha1 = "6fe4202f29714244b84496d38da46eb65f7b63a7"
os = "windows"

    [[CSPICE.download]]
    sha256 = "927b07cea6c8f5357ea92c491680a4b7fbd021245085d16450079a143a422a35"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.0.0+1/CSPICE.v66.0.0.i686-w64-mingw32.tar.gz"
[[CSPICE]]
arch = "powerpc64le"
git-tree-sha1 = "5887ccc998a72286bfebde33d0c0c91e0f65369a"
libc = "glibc"
os = "linux"

    [[CSPICE.download]]
    sha256 = "5a08473d629dd0e47c81fef746022bc28c7d5be89f95e61bce4947103ed004eb"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.0.0+1/CSPICE.v66.0.0.powerpc64le-linux-gnu.tar.gz"
[[CSPICE]]
arch = "x86_64"
git-tree-sha1 = "b96efbd6b9f620ca63d15bcdbe71874490f4e190"
os = "macos"

    [[CSPICE.download]]
    sha256 = "d6142ea6b5039a3295bb6e42d9d4b645af35ec12da756f30106efb53ccb269c8"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.0.0+1/CSPICE.v66.0.0.x86_64-apple-darwin14.tar.gz"
[[CSPICE]]
arch = "x86_64"
git-tree-sha1 = "9793581bb0cacefeed076c62196272db62ec3683"
libc = "glibc"
os = "linux"

    [[CSPICE.download]]
    sha256 = "b64740ff08d949b29b206f1945d06bf15fff86870757a1bcb07e885cc3ac9a9c"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.0.0+1/CSPICE.v66.0.0.x86_64-linux-gnu.tar.gz"
[[CSPICE]]
arch = "x86_64"
git-tree-sha1 = "8db78c518125cbc1ba048d9289b1225f8b15da97"
libc = "musl"
os = "linux"

    [[CSPICE.download]]
    sha256 = "0e3ff001693a63c506063b38cccf0c41831c37741b7f7ee8965a89d6195dc363"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.0.0+1/CSPICE.v66.0.0.x86_64-linux-musl.tar.gz"
[[CSPICE]]
arch = "x86_64"
git-tree-sha1 = "1cf16a15620879921a5f9a1486925fd5b1713e95"
os = "freebsd"

    [[CSPICE.download]]
    sha256 = "3cdb496c8e57888899f113a814be7c5e59e47b8396bbdf73a6edf7ea3dfaf75f"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.0.0+1/CSPICE.v66.0.0.x86_64-unknown-freebsd11.1.tar.gz"
[[CSPICE]]
arch = "x86_64"
git-tree-sha1 = "eb646d47bf4e28c02b8689ca5af1286f50b62313"
os = "windows"

    [[CSPICE.download]]
    sha256 = "2989a78d3c075855f61622c8cc934d6d0bf18064b8859b8986cce681f939f2de"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.0.0+1/CSPICE.v66.0.0.x86_64-w64-mingw32.tar.gz"
