[[CSPICE]]
arch = "aarch64"
git-tree-sha1 = "ea1c42c5a9aaa93d5252bd37ab740c6448eefa19"
libc = "glibc"
os = "linux"

    [[CSPICE.download]]
    sha256 = "d385405dea19ab25e04c0b62e046cbc4d0c02cd057273dba84db50d4ce5831ae"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.1.0+0/CSPICE.v66.1.0.aarch64-linux-gnu.tar.gz"
[[CSPICE]]
arch = "aarch64"
git-tree-sha1 = "829d0387e3a9a6d4eabc2ef50345a2059ef6632c"
libc = "musl"
os = "linux"

    [[CSPICE.download]]
    sha256 = "e5b9b5ef9c08beb87ead962fe27b16a08c334be4559001dee19a6df9e3df415b"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.1.0+0/CSPICE.v66.1.0.aarch64-linux-musl.tar.gz"
[[CSPICE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1b198e5a035506aba02cc0c27df55439d8be986d"
libc = "glibc"
os = "linux"

    [[CSPICE.download]]
    sha256 = "b4ee848bb2afbde34b68f43045604ff359d9cefdd8abf0273f773f98d20fb13e"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.1.0+0/CSPICE.v66.1.0.armv7l-linux-gnueabihf.tar.gz"
[[CSPICE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "93202fcefb7391b65be34a99822cdc75f1681fab"
libc = "musl"
os = "linux"

    [[CSPICE.download]]
    sha256 = "efc97033cbb1b62b40a2aa33acb57e06deb3f03dacfda141ab9b93e8e4918c2a"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.1.0+0/CSPICE.v66.1.0.armv7l-linux-musleabihf.tar.gz"
[[CSPICE]]
arch = "i686"
git-tree-sha1 = "07e800fdcb01a03829e45877cdfcd5b9219059f7"
libc = "glibc"
os = "linux"

    [[CSPICE.download]]
    sha256 = "06b75f85d27d2d5093b6f1a99fa27555692b526f0121a9f2b4a4cb773879f07f"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.1.0+0/CSPICE.v66.1.0.i686-linux-gnu.tar.gz"
[[CSPICE]]
arch = "i686"
git-tree-sha1 = "25e95636ad5a76da55de8d250a42a5459f2ba567"
libc = "musl"
os = "linux"

    [[CSPICE.download]]
    sha256 = "2972a0fc2a5dd31b2021838f1a04d73c5216b45d3bded892fe00a910d3c435cb"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.1.0+0/CSPICE.v66.1.0.i686-linux-musl.tar.gz"
[[CSPICE]]
arch = "i686"
git-tree-sha1 = "4c2e4da30857bac8508a54e7b9af3c825253d040"
os = "windows"

    [[CSPICE.download]]
    sha256 = "359683056868de0ba5cf31344522322a90fcb15d57c323827e713cf489d0048c"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.1.0+0/CSPICE.v66.1.0.i686-w64-mingw32.tar.gz"
[[CSPICE]]
arch = "powerpc64le"
git-tree-sha1 = "dde415b9e36a93ab8be00c010e7b05f2cbf4d457"
libc = "glibc"
os = "linux"

    [[CSPICE.download]]
    sha256 = "067fc442df5c162158c65293100caa56f25ce9fe134ad8f4bb3867b45790b45f"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.1.0+0/CSPICE.v66.1.0.powerpc64le-linux-gnu.tar.gz"
[[CSPICE]]
arch = "x86_64"
git-tree-sha1 = "e3e26928ae00c0987a45a9f3b4da94c31109b8ad"
os = "macos"

    [[CSPICE.download]]
    sha256 = "60333d5bdfacc781fada4cf646f3bf99465cc1f20d5bcada1d7fa6da6ff46bbd"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.1.0+0/CSPICE.v66.1.0.x86_64-apple-darwin.tar.gz"
[[CSPICE]]
arch = "x86_64"
git-tree-sha1 = "bdf6189248fb87841bb369cb109538df63c21f27"
libc = "glibc"
os = "linux"

    [[CSPICE.download]]
    sha256 = "55600faa5854324292b595ab337060c2bf2255dddb13ea314888cf9f884fcc1e"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.1.0+0/CSPICE.v66.1.0.x86_64-linux-gnu.tar.gz"
[[CSPICE]]
arch = "x86_64"
git-tree-sha1 = "27d5769588f2b2ef9bd02791dd554a12b1b2f6f2"
libc = "musl"
os = "linux"

    [[CSPICE.download]]
    sha256 = "2759bb05ecbcf34598907c4a32522031b3bdd9b471e0e3a57412c3eee658575a"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.1.0+0/CSPICE.v66.1.0.x86_64-linux-musl.tar.gz"
[[CSPICE]]
arch = "x86_64"
git-tree-sha1 = "b3de40185d0cb92898deee76b739dcb2e149dcc4"
os = "freebsd"

    [[CSPICE.download]]
    sha256 = "bc20f2af8073d49b32fc2a6000f226b5098e51eb2aced6fe5c54d99f62a8acc3"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.1.0+0/CSPICE.v66.1.0.x86_64-unknown-freebsd.tar.gz"
[[CSPICE]]
arch = "x86_64"
git-tree-sha1 = "898e308dae2684c5436edae466a5bcfa4a8067ef"
os = "windows"

    [[CSPICE.download]]
    sha256 = "aa61c131127ad9ac43b1b1e4cd9db279702a27c64341229a31545481a0edcb6b"
    url = "https://github.com/JuliaBinaryWrappers/CSPICE_jll.jl/releases/download/CSPICE-v66.1.0+0/CSPICE.v66.1.0.x86_64-w64-mingw32.tar.gz"
