# Autogenerated wrapper script for CSPICE_jll for x86_64-w64-mingw32
export brief, chronos, ckbrief, commnt, dskbrief, dskexp, frmdiff, inspekt, libcspice, libcsupport, mkdsk, mkspk, msopck, spacit, spkdiff, spkmerge, tobin, toxfr, version

JLLWrappers.@generate_wrapper_header("CSPICE")
JLLWrappers.@declare_executable_product(brief)
JLLWrappers.@declare_executable_product(chronos)
JLLWrappers.@declare_executable_product(ckbrief)
JLLWrappers.@declare_executable_product(commnt)
JLLWrappers.@declare_executable_product(dskbrief)
JLLWrappers.@declare_executable_product(dskexp)
JLLWrappers.@declare_executable_product(frmdiff)
JLLWrappers.@declare_executable_product(inspekt)
JLLWrappers.@declare_library_product(libcspice, "libcspice.dll")
JLLWrappers.@declare_library_product(libcsupport, "libcsupport.dll")
JLLWrappers.@declare_executable_product(mkdsk)
JLLWrappers.@declare_executable_product(mkspk)
JLLWrappers.@declare_executable_product(msopck)
JLLWrappers.@declare_executable_product(spacit)
JLLWrappers.@declare_executable_product(spkdiff)
JLLWrappers.@declare_executable_product(spkmerge)
JLLWrappers.@declare_executable_product(tobin)
JLLWrappers.@declare_executable_product(toxfr)
JLLWrappers.@declare_executable_product(version)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        brief,
        "bin\\brief.exe",
    )

    JLLWrappers.@init_executable_product(
        chronos,
        "bin\\chronos.exe",
    )

    JLLWrappers.@init_executable_product(
        ckbrief,
        "bin\\ckbrief.exe",
    )

    JLLWrappers.@init_executable_product(
        commnt,
        "bin\\commnt.exe",
    )

    JLLWrappers.@init_executable_product(
        dskbrief,
        "bin\\dskbrief.exe",
    )

    JLLWrappers.@init_executable_product(
        dskexp,
        "bin\\dskexp.exe",
    )

    JLLWrappers.@init_executable_product(
        frmdiff,
        "bin\\frmdiff.exe",
    )

    JLLWrappers.@init_executable_product(
        inspekt,
        "bin\\inspekt.exe",
    )

    JLLWrappers.@init_library_product(
        libcspice,
        "bin\\libcspice.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcsupport,
        "bin\\libcsupport.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        mkdsk,
        "bin\\mkdsk.exe",
    )

    JLLWrappers.@init_executable_product(
        mkspk,
        "bin\\mkspk.exe",
    )

    JLLWrappers.@init_executable_product(
        msopck,
        "bin\\msopck.exe",
    )

    JLLWrappers.@init_executable_product(
        spacit,
        "bin\\spacit.exe",
    )

    JLLWrappers.@init_executable_product(
        spkdiff,
        "bin\\spkdiff.exe",
    )

    JLLWrappers.@init_executable_product(
        spkmerge,
        "bin\\spkmerge.exe",
    )

    JLLWrappers.@init_executable_product(
        tobin,
        "bin\\tobin.exe",
    )

    JLLWrappers.@init_executable_product(
        toxfr,
        "bin\\toxfr.exe",
    )

    JLLWrappers.@init_executable_product(
        version,
        "bin\\version.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
